image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: "mongodb://mongo/user_posts"

build_job:
  stage: build
  before_script:
    - cd reddit
    - bundle install
#    - docker info
  services:
    - mongo:latest
  script:
    - docker build -t avastr/ui:1.0 ./src/ui
    - docker build -t avastr/comment:1.0 ./src/comment
    - docker build -t avastr/post:1.0 ./src/post-py
    - docker run -d --network=reddit mongo:latest
    - docker run -d --network=reddit --network-alias=post avastr/post:1.0
    - docker run -d --network=reddit --network-alias=post_db --network-alias=comment_db mongo:latest
    - docker run -d --network=reddit --network-alias=comment avastr/comment:1.0
    - docker run -d --network=reddit -p 9292:9292 avastr/ui:1.0
    - ruby simpletest.rb
test_unit_job:
  stage: test
  script:
    - echo "Testing 1"

test_integration_job:
  stage: test
  script:
    - echo "Testing 2"

deploy_dev_job:
  stage: review
  script:
    - echo "Deploy"
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo "Deploy"
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo "'Deploy"
  environment:
    name: production
    url: https://example.com
