dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
notifications:
  slack:
    secure: DmiMyPsOwJ5k1FQcIklHykK8hM8V2Ia4VlxzTY9RbJvsudCYxvAN3J/vQ5IWl1Y32UX+gnvAgq2WbpA9bLhWnbtrQa57hXh1R6G45PfN0ZSnPu7XxycVJl0YVXy3Fr2ULnrucP7kZEduEnN0g2A6HWSQa26j8CUHJpUjIvboebFzANmacqhTe0YDeleu0qCbtasU8XGYoxL9iyAGIOxm0BFoWkZ6tAyq4kCXcjh6n9xn+LXyyD+1JxBJb4mrc40EzOFay9lvYijEUvzCUbjDTK9MWWkiMzL3I5sxZToZXrI+u1MaE+6M3XCs/WBBsOXRvaFyCHFnzM3XB8n7AnQEl8PIeUO5kKRe8qYF7o0zKrxi7oJm0tcp6gWDgc0WXVuXydEjTqKcfXuY/N2PJhRZCx+CM3kB2Bw9nbb8Vi4KsX+AUVdnaP3bSRPhO9R0XaX+wgnwT3zthCO8plOQ77X8JpdkZJBUg7xJbBsqu+Rm9uRMYKXpp7Ix1ZnHeFH1kdu3yJn++bFkbNOXM8Kqa5LbcLG+aALtLJ3hkUYE28UVbwWCHKHRb+iGvmiB2ksLLvWr+zBavQOyG3PuhX+Rc5b5ezNlkVbdbsWYxfgbNzVzwAJQfaL8lm2QgngS2dAXH63Hi/4s0n5t+PwrKPH+ITG+14fvqqyJ9I/O9ic5uf05PHE=
