dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
notifications:
  slack:
    secure: d/wonCTnlzeISVpXP5L1UPfEc2hqHjOJpajo2BI5hS7BrfY08Z11H1gV2U69OEw1cmQ1OWo8BrXdpiLmSGoq4gFYg0W2KlW1KTUN3OfdiKTiYFJUqicd7NwT0+W3VDF7frADQYm4kogmZr7apsMuc61NF+t4fQ7BfEyEMKIp4GSh3wLKn1uUeJAzoi0DK/90yyCGKQdhi1qNu5Fj60mccXoaZtOBC4tzs8/B2AgJIsnQ9hRhZ4cTDTGrAUe3Rh9LfRL8xtwNAUBWotWJ0DvKbHjrj7UByNKlFThF/iw6sPDg9x/i7CAWH2a8dRqDnZQaOaHPNHjFq2/n3woWWvkyh7LxrA1j6x+FGd6ioZX99ELY8OljqlcUT+nf3Spi5SULoRueSoIg7HTLApjvsOZm8Dhc7r/cwS5W3Xw/Kst5sZOBr1yB5A/xxAasthWX58Y8DwUXRK8hTpln+UOLaxPxrxAKcYSj/wSdWSBSiIIcMHEJQVUeJt47BA10IYRFBeK++PbKxO7U4uF3NUPvWFW8tQ19eOxHc0hgNWq42SiS7Hz30cMZrqrzaaDgILRidJL+ZKcnKF6b9TeRHG7+9PO2miwVXXijjrcJmdaZ4bO8Ylz8gzWwpeuUewx90K90zfjkQcymvHD10xGoIaCXTWw/voUyBfo8kEz52wwhXYRYyfw=
