dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
notifications:
  slack:
    secure: t+Qu60lzg5oUKtYEn/v3X+UX7COxuA0QtPVd8smfKoKVq+YrqAGd6qtVXIeA/7w5n4CD33+6yH9vkM052MUPZ5i9OvXZLPs3hwtb3cvXP7unUZhiuOZrHtLZB33+d+ENHQie/PXeMVVeFISzW0176Pr6HaJaDALzBIPUQmN0fZTTtzx0HCHKYnuAOjDvmKwhqKixZePvRSh70jr5T4I5I51uMYEMlI0AlcqJn45ag/C59tj11UjlTGRp1w4lXIFfmDzb1mZlwgVxuJyMdd4SusQ+1kS8UHttoFcvbi+Y3BluFZCWRlel4zTuOAbPMc6r+z9kd44/Ec1s+K0RGIXdgBbJ4sPKH+lZ/K0NQbKytOr57QbMP1g8er6wBKPIfLvy9xlmMhzcsqrz9ds1WYjKZy6czTMUG/3IMRRiwsV2aYV4LElqr63MNUqv+MAhbiyotxf8qawRZCMr0QM9mWBtuuW9BwTsHKZ96atDObS83fgtO7158qRmtEucMuZ1TqyVAnN04IFnYtZ9Y93DimCe3Heo/6IbH07MSk+Ju/XtUKWgb+N/2QO7+BP1PAVywwOZ7zp9AcfLi00qE74zoVrA2OXFDAJJvBuFQxWGOXHgko0zzw0Q4uQKJOjyRR7+woGPiiGv01vouzF5sGwCGE0aUEzJuF+BEm02Bow7V27KxCA=
