dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh | bash
travis encrypt "devops-team-otus:fRx2oRAAASRM1R1CgjUkh80R" --add notifications.slack -r avastr/AVAstr_mocroservices
