version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - ${FRONT}
      - ${BACK}
  ui:
    image: ${USER_NAME}/ui:${VERSION}
    ports:
      - 9292:${PORT}/tcp
    networks:
      - ${FRONT}
      - ${BACK}
  post:
    image: ${USER_NAME}/post:${VERSION}
    networks:
      - ${BACK}
      - ${FRONT}
  comment:
    image: ${USER_NAME}/comment:${VERSION}
    networks:
      - ${BACK}
      - ${FRONT}

volumes:
  post_db:

networks:
  front_net:
  back_net:
