version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - ${FRONT}
      - ${BACK}
  ui:
    image: ${USERNAME}/ui:${VERSION}
    ports:
      - 9292:${PORT}/tcp
    networks:
      - ${FRONT}
  post:
    image: ${USERNAME}/post:${VERSION}
    networks:
      - ${BACK}
      - ${FRONT}
  comment:
    image: ${USERNAME}/comment:${VERSION}
    networks:
      - ${BACK}
      - ${FRONT}
  prometheus:
    image: ${USERNAME}/prometheus
    networks:
      - ${BACK}
      - ${FRONT}
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
  node-exporter:
    image: prom/node-exporter:v0.15.2
    networks:
      - ${BACK}
      - ${FRONT}
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
