{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prom.serviceAccountName" . }}
  labels:
{{ include "prom.labels" . | indent 4 }}
{{- end -}}
